roboptim-core-plugin-cminpack: roboptim::cminpack::SolverWithJacobian Class Reference
roboptim::cminpack::SolverWithJacobian Class Reference
Solver implementing a variant of Levenberg-Marquardt algorithm.
#include <roboptim/core/plugin/cminpack.hh>
Public Types
typedef Solver< SumOfC1Squares,
boost::mpl::vector<> > parent_t
Parent type.
typedef problem_t::function_t function_t
Cost function type.
typedef parent_t::result_t result_t
type of result
typedef
DerivableFunction::gradient_t gradient_t
type of gradient
typedef Function::size_type size_type
Size type.
Public Member Functions
SolverWithJacobian (const problem_t &problem)
Constructot by problem.
virtual ~SolverWithJacobian () throw ()
virtual void solve () throw ()
Solve the optimization problem.
int n () const
Number of variables.
int m () const
Number of functions.
Function::argument_t & parameter ()
Get parameter.
const Function::argument_t & parameter () const
const Function::argument_t & value () const
Get value.
const gradient_t & jacobianRow (size_t iRow) const
Get Jacobian.
Detailed Description
Solver implementing a variant of Levenberg-Marquardt algorithm.
This solver tries to minimize the euclidean norm of a vector valued function.
Member Typedef Documentation
typedef problem_t::function_t roboptim::cminpack::SolverWithJacobian::function_t
Cost function type.
typedef DerivableFunction::gradient_t roboptim::cminpack::SolverWithJacobian::gradient_t
type of gradient
typedef Solver<SumOfC1Squares, boost::mpl::vector<> > roboptim::cminpack::SolverWithJacobian::parent_t
Parent type.
typedef parent_t::result_t roboptim::cminpack::SolverWithJacobian::result_t
type of result
typedef Function::size_type roboptim::cminpack::SolverWithJacobian::size_type
Size type.
Constructor & Destructor Documentation
roboptim::cminpack::SolverWithJacobian::SolverWithJacobian (const problem_t & problem) [explicit]
Constructot by problem.
roboptim::cminpack::SolverWithJacobian::~SolverWithJacobian () throw () [virtual]
Member Function Documentation
const gradient_t& roboptim::cminpack::SolverWithJacobian::jacobianRow (size_t iRow) const [inline]
Get Jacobian.
Referenced by roboptim_plugin_cminpack_fcn().
int roboptim::cminpack::SolverWithJacobian::m () const [inline]
Number of functions.
Referenced by roboptim_plugin_cminpack_fcn().
int roboptim::cminpack::SolverWithJacobian::n () const [inline]
Number of variables.
Referenced by roboptim_plugin_cminpack_fcn().
const Function::argument_t& roboptim::cminpack::SolverWithJacobian::parameter () const [inline]
Function::argument_t& roboptim::cminpack::SolverWithJacobian::parameter () [inline]
Get parameter.
Referenced by roboptim_plugin_cminpack_fcn().
void roboptim::cminpack::SolverWithJacobian::solve () throw () [virtual]
Solve the optimization problem.
References roboptim_plugin_cminpack_fcn().
const Function::argument_t& roboptim::cminpack::SolverWithJacobian::value () const [inline]
Get value.
Referenced by roboptim_plugin_cminpack_fcn().