roboptim-core-plugin-cminpack: cminpack.cc File Reference
cminpack.cc File Reference
#include <cminpack.h>
#include "roboptim/core/function.hh"
#include "roboptim/core/problem.hh"
#include "roboptim/core/solver-error.hh"
#include "roboptim/core/plugin/cminpack.hh"
Namespaces
namespace roboptim
namespace roboptim::cminpack
Typedefs
typedef
SolverWithJacobian::parent_t solver_t
Functions
void roboptim::cminpack::matrix_to_array (Function::value_type *dst, const Function::matrix_t &src, int iRow)
int roboptim_plugin_cminpack_fcn (void *p, int m, int n, const double *x, double *fvec, double *fjrow, int iflag)
ROBOPTIM_DLLEXPORT unsigned getSizeOfProblem ()
ROBOPTIM_DLLEXPORT solver_t * create (const SolverWithJacobian::problem_t &pb)
ROBOPTIM_DLLEXPORT void destroy (solver_t *p)
Typedef Documentation
typedef SolverWithJacobian::parent_t solver_t
Function Documentation
ROBOPTIM_DLLEXPORT solver_t * create (const SolverWithJacobian::problem_t & pb)
ROBOPTIM_DLLEXPORT void destroy (solver_t * p)
ROBOPTIM_DLLEXPORT unsigned getSizeOfProblem ()
int roboptim_plugin_cminpack_fcn (void * p, int m, int n, const double * x, double * fvec, double * fjrow, int iflag)
References roboptim::cminpack::SolverWithJacobian::jacobianRow(), roboptim::cminpack::SolverWithJacobian::m(), roboptim::cminpack::SolverWithJacobian::n(), roboptim::cminpack::SolverWithJacobian::parameter(), and roboptim::cminpack::SolverWithJacobian::value().
Referenced by roboptim::cminpack::SolverWithJacobian::solve().